-- =============================================
-- Migration: Points Relais Complets (58 wilayas)
-- Transporteurs: ZR Express, Yalidine, Noest, DHD, Ecotrack PDEX
-- =============================================

-- Supprimer l'ancienne data limitée
DELETE FROM stop_desks WHERE transporteur IN ('Yalidine','ZR Express','Noest','DHD','Ecotrack PDEX');

-- =============================================
-- ZR EXPRESS - Agences dans les 58 wilayas
-- =============================================
INSERT OR IGNORE INTO stop_desks (name, wilaya_id, transporteur, address) VALUES
('Agence ZR Adrar Centre', 1, 'ZR Express', 'Rue principale, Adrar'),
('Agence ZR Chlef Centre', 2, 'ZR Express', 'Boulevard de l''indépendance, Chlef'),
('Agence ZR Chlef Oued Fodda', 2, 'ZR Express', 'Oued Fodda, Chlef'),
('Agence ZR Laghouat Centre', 3, 'ZR Express', 'Rue Larbi Ben M''hidi, Laghouat'),
('Agence ZR Oum El Bouaghi', 4, 'ZR Express', 'Centre ville, Oum El Bouaghi'),
('Agence ZR Ain Beida', 4, 'ZR Express', 'Ain Beida, Oum El Bouaghi'),
('Agence ZR Batna Centre', 5, 'ZR Express', 'Rue du 1er novembre, Batna'),
('Agence ZR Batna Ain Touta', 5, 'ZR Express', 'Ain Touta, Batna'),
('Agence ZR Bejaia Centre', 6, 'ZR Express', 'Boulevard Amirouche, Bejaia'),
('Agence ZR Bejaia Akbou', 6, 'ZR Express', 'Akbou, Bejaia'),
('Agence ZR Biskra Centre', 7, 'ZR Express', 'Avenue du 1er novembre, Biskra'),
('Agence ZR Biskra Tolga', 7, 'ZR Express', 'Tolga, Biskra'),
('Agence ZR Bechar Centre', 8, 'ZR Express', 'Rue Larbi Ben M''hidi, Bechar'),
('Agence ZR Blida Centre', 9, 'ZR Express', 'Boulevard Colonel Lotfi, Blida'),
('Agence ZR Blida Boufarik', 9, 'ZR Express', 'Boufarik, Blida'),
('Agence ZR Blida Bougara', 9, 'ZR Express', 'Bougara, Blida'),
('Agence ZR Bouira Centre', 10, 'ZR Express', 'Rue Amirouche, Bouira'),
('Agence ZR Bouira Lakhdaria', 10, 'ZR Express', 'Lakhdaria, Bouira'),
('Agence ZR Tamanrasset', 11, 'ZR Express', 'Centre ville, Tamanrasset'),
('Agence ZR Tebessa Centre', 12, 'ZR Express', 'Rue du 1er novembre, Tebessa'),
('Agence ZR Tlemcen Centre', 13, 'ZR Express', 'Place Emir Abdelkader, Tlemcen'),
('Agence ZR Tlemcen Maghnia', 13, 'ZR Express', 'Maghnia, Tlemcen'),
('Agence ZR Tiaret Centre', 14, 'ZR Express', 'Boulevard de la République, Tiaret'),
('Agence ZR Tizi Ouzou Centre', 15, 'ZR Express', 'Rue Abane Ramdane, Tizi Ouzou'),
('Agence ZR Tizi Ouzou Azazga', 15, 'ZR Express', 'Azazga, Tizi Ouzou'),
('Agence ZR Tizi Ouzou Draa El Mizan', 15, 'ZR Express', 'Draa El Mizan, Tizi Ouzou'),
('Agence ZR Alger Bab Ezzouar', 16, 'ZR Express', 'Quartier d''affaires, Bab Ezzouar'),
('Agence ZR Alger Hussein Dey', 16, 'ZR Express', 'Hussein Dey, Alger'),
('Agence ZR Alger Dar El Beida', 16, 'ZR Express', 'Dar El Beida, Alger'),
('Agence ZR Alger Baraki', 16, 'ZR Express', 'Baraki, Alger'),
('Agence ZR Alger Birkhadem', 16, 'ZR Express', 'Birkhadem, Alger'),
('Agence ZR Alger Rouiba', 16, 'ZR Express', 'Rouiba, Alger'),
('Agence ZR Djelfa Centre', 17, 'ZR Express', 'Avenue du 1er novembre, Djelfa'),
('Agence ZR Jijel Centre', 18, 'ZR Express', 'Rue Larbi Ben M''hidi, Jijel'),
('Agence ZR Setif Centre', 19, 'ZR Express', 'Boulevard du 8 Mai 1945, Setif'),
('Agence ZR Setif El Eulma', 19, 'ZR Express', 'El Eulma, Setif'),
('Agence ZR Saida Centre', 20, 'ZR Express', 'Rue du 1er novembre, Saida'),
('Agence ZR Skikda Centre', 21, 'ZR Express', 'Boulevard du 20 Août, Skikda'),
('Agence ZR Sidi Bel Abbes Centre', 22, 'ZR Express', 'Avenue de l''ANL, Sidi Bel Abbes'),
('Agence ZR Annaba Centre', 23, 'ZR Express', 'Cours de la Révolution, Annaba'),
('Agence ZR Annaba El Bouni', 23, 'ZR Express', 'El Bouni, Annaba'),
('Agence ZR Guelma Centre', 24, 'ZR Express', 'Rue Larbi Ben M''hidi, Guelma'),
('Agence ZR Constantine Centre', 25, 'ZR Express', 'Rue Didouche Mourad, Constantine'),
('Agence ZR Constantine Ain Smara', 25, 'ZR Express', 'Ain Smara, Constantine'),
('Agence ZR Medea Centre', 26, 'ZR Express', 'Avenue du 1er novembre, Medea'),
('Agence ZR Mostaganem Centre', 27, 'ZR Express', 'Boulevard du 5 Juillet, Mostaganem'),
('Agence ZR Msila Centre', 28, 'ZR Express', 'Rue du 1er novembre, M''Sila'),
('Agence ZR Mascara Centre', 29, 'ZR Express', 'Rue Larbi Ben M''hidi, Mascara'),
('Agence ZR Ouargla Centre', 30, 'ZR Express', 'Avenue du 1er novembre, Ouargla'),
('Agence ZR Oran Es Senia', 31, 'ZR Express', 'Zone commerciale, Es Senia'),
('Agence ZR Oran Bir El Djir', 31, 'ZR Express', 'Bir El Djir, Oran'),
('Agence ZR Oran Sidi Maarouf', 31, 'ZR Express', 'Sidi Maarouf, Oran'),
('Agence ZR El Bayadh', 32, 'ZR Express', 'Centre ville, El Bayadh'),
('Agence ZR Illizi', 33, 'ZR Express', 'Centre ville, Illizi'),
('Agence ZR Bordj Bou Arreridj Centre', 34, 'ZR Express', 'Avenue Larbi Ben M''hidi, Bordj Bou Arreridj'),
('Agence ZR Boumerdes Centre', 35, 'ZR Express', 'Rue Bouali Said, Boumerdes'),
('Agence ZR Boumerdes Khemis El Khechna', 35, 'ZR Express', 'Khemis El Khechna, Boumerdes'),
('Agence ZR El Tarf Centre', 36, 'ZR Express', 'Centre ville, El Tarf'),
('Agence ZR Tindouf', 37, 'ZR Express', 'Centre ville, Tindouf'),
('Agence ZR Tissemsilt', 38, 'ZR Express', 'Centre ville, Tissemsilt'),
('Agence ZR El Oued Centre', 39, 'ZR Express', 'Avenue Hassi Messaoud, El Oued'),
('Agence ZR Khenchela Centre', 40, 'ZR Express', 'Rue du 1er novembre, Khenchela'),
('Agence ZR Souk Ahras Centre', 41, 'ZR Express', 'Rue Larbi Ben M''hidi, Souk Ahras'),
('Agence ZR Tipaza Centre', 42, 'ZR Express', 'Rue du 1er novembre, Tipaza'),
('Agence ZR Tipaza Kolea', 42, 'ZR Express', 'Kolea, Tipaza'),
('Agence ZR Mila Centre', 43, 'ZR Express', 'Centre ville, Mila'),
('Agence ZR Ain Defla Centre', 44, 'ZR Express', 'Rue de l''indépendance, Ain Defla'),
('Agence ZR Naama Centre', 45, 'ZR Express', 'Centre ville, Naama'),
('Agence ZR Ain Temouchent Centre', 46, 'ZR Express', 'Boulevard du 1er novembre, Ain Temouchent'),
('Agence ZR Ghardaia Centre', 47, 'ZR Express', 'Avenue du 1er novembre, Ghardaia'),
('Agence ZR Relizane Centre', 48, 'ZR Express', 'Rue de la Révolution, Relizane'),
('Agence ZR Timimoun', 49, 'ZR Express', 'Centre ville, Timimoun'),
('Agence ZR Bordj Badji Mokhtar', 50, 'ZR Express', 'Centre ville, Bordj Badji Mokhtar'),
('Agence ZR Ouled Djellal', 51, 'ZR Express', 'Centre ville, Ouled Djellal'),
('Agence ZR Beni Abbes', 52, 'ZR Express', 'Centre ville, Beni Abbes'),
('Agence ZR In Salah', 53, 'ZR Express', 'Centre ville, In Salah'),
('Agence ZR In Guezzam', 54, 'ZR Express', 'Centre ville, In Guezzam'),
('Agence ZR Touggourt Centre', 55, 'ZR Express', 'Centre ville, Touggourt'),
('Agence ZR Djanet', 56, 'ZR Express', 'Centre ville, Djanet'),
('Agence ZR El Meghaier', 57, 'ZR Express', 'Centre ville, El Meghaier'),
('Agence ZR El Meniaa', 58, 'ZR Express', 'Centre ville, El Meniaa');

-- =============================================
-- YALIDINE - Hubs/Centres dans les 58 wilayas
-- =============================================
INSERT OR IGNORE INTO stop_desks (name, wilaya_id, transporteur, address) VALUES
('Hub Yalidine Adrar', 1, 'Yalidine', 'Centre ville, Adrar'),
('Hub Yalidine Chlef Centre', 2, 'Yalidine', 'Chlef Centre'),
('Hub Yalidine Laghouat', 3, 'Yalidine', 'Centre ville, Laghouat'),
('Hub Yalidine Oum El Bouaghi', 4, 'Yalidine', 'Centre ville, Oum El Bouaghi'),
('Hub Yalidine Batna Centre', 5, 'Yalidine', 'Rue du 1er novembre, Batna'),
('Hub Yalidine Bejaia Centre', 6, 'Yalidine', 'Boulevard Amirouche, Bejaia'),
('Hub Yalidine Bejaia Akbou', 6, 'Yalidine', 'Zone industrielle, Akbou'),
('Hub Yalidine Biskra Centre', 7, 'Yalidine', 'Avenue du 1er novembre, Biskra'),
('Hub Yalidine Bechar', 8, 'Yalidine', 'Centre ville, Bechar'),
('Hub Yalidine Blida Centre', 9, 'Yalidine', 'Boulevard Colonel Lotfi, Blida'),
('Hub Yalidine Bouira', 10, 'Yalidine', 'Centre ville, Bouira'),
('Hub Yalidine Tamanrasset', 11, 'Yalidine', 'Centre ville, Tamanrasset'),
('Hub Yalidine Tebessa', 12, 'Yalidine', 'Centre ville, Tebessa'),
('Hub Yalidine Tlemcen Centre', 13, 'Yalidine', 'Place Emir Abdelkader, Tlemcen'),
('Hub Yalidine Tiaret', 14, 'Yalidine', 'Centre ville, Tiaret'),
('Hub Yalidine Tizi Ouzou Centre', 15, 'Yalidine', 'Rue du 1er novembre, Tizi Ouzou'),
('Hub Yalidine Alger Centre', 16, 'Yalidine', 'Didouche Mourad, Alger'),
('Hub Yalidine Alger Birkhadem', 16, 'Yalidine', 'Les Vergers, Birkhadem'),
('Hub Yalidine Alger Rouiba', 16, 'Yalidine', 'Zone industrielle, Rouiba'),
('Hub Yalidine Alger Dar El Beida', 16, 'Yalidine', 'Dar El Beida, Alger'),
('Hub Yalidine Djelfa', 17, 'Yalidine', 'Centre ville, Djelfa'),
('Hub Yalidine Jijel', 18, 'Yalidine', 'Centre ville, Jijel'),
('Hub Yalidine Setif Centre', 19, 'Yalidine', 'Zone industrielle, Setif'),
('Hub Yalidine Setif El Eulma', 19, 'Yalidine', 'El Eulma, Setif'),
('Hub Yalidine Saida', 20, 'Yalidine', 'Centre ville, Saida'),
('Hub Yalidine Skikda', 21, 'Yalidine', 'Centre ville, Skikda'),
('Hub Yalidine Sidi Bel Abbes', 22, 'Yalidine', 'Centre ville, Sidi Bel Abbes'),
('Hub Yalidine Annaba Centre', 23, 'Yalidine', 'Cours de la Révolution, Annaba'),
('Hub Yalidine Guelma', 24, 'Yalidine', 'Centre ville, Guelma'),
('Hub Yalidine Constantine Centre', 25, 'Yalidine', 'Belouizdad, Constantine'),
('Hub Yalidine Medea', 26, 'Yalidine', 'Centre ville, Medea'),
('Hub Yalidine Mostaganem', 27, 'Yalidine', 'Centre ville, Mostaganem'),
('Hub Yalidine Msila', 28, 'Yalidine', 'Centre ville, M''Sila'),
('Hub Yalidine Mascara', 29, 'Yalidine', 'Centre ville, Mascara'),
('Hub Yalidine Ouargla', 30, 'Yalidine', 'Centre ville, Ouargla'),
('Hub Yalidine Oran City', 31, 'Yalidine', 'Centre Ville, Oran'),
('Hub Yalidine Oran Es Senia', 31, 'Yalidine', 'Es Senia, Oran'),
('Hub Yalidine El Bayadh', 32, 'Yalidine', 'Centre ville, El Bayadh'),
('Hub Yalidine Illizi', 33, 'Yalidine', 'Centre ville, Illizi'),
('Hub Yalidine Bordj Bou Arreridj', 34, 'Yalidine', 'Centre ville, Bordj Bou Arreridj'),
('Hub Yalidine Boumerdes', 35, 'Yalidine', 'Centre ville, Boumerdes'),
('Hub Yalidine El Tarf', 36, 'Yalidine', 'Centre ville, El Tarf'),
('Hub Yalidine Tindouf', 37, 'Yalidine', 'Centre ville, Tindouf'),
('Hub Yalidine Tissemsilt', 38, 'Yalidine', 'Centre ville, Tissemsilt'),
('Hub Yalidine El Oued', 39, 'Yalidine', 'Centre ville, El Oued'),
('Hub Yalidine Khenchela', 40, 'Yalidine', 'Centre ville, Khenchela'),
('Hub Yalidine Souk Ahras', 41, 'Yalidine', 'Centre ville, Souk Ahras'),
('Hub Yalidine Tipaza', 42, 'Yalidine', 'Centre ville, Tipaza'),
('Hub Yalidine Mila', 43, 'Yalidine', 'Centre ville, Mila'),
('Hub Yalidine Ain Defla', 44, 'Yalidine', 'Centre ville, Ain Defla'),
('Hub Yalidine Naama', 45, 'Yalidine', 'Centre ville, Naama'),
('Hub Yalidine Ain Temouchent', 46, 'Yalidine', 'Centre ville, Ain Temouchent'),
('Hub Yalidine Ghardaia', 47, 'Yalidine', 'Centre ville, Ghardaia'),
('Hub Yalidine Relizane', 48, 'Yalidine', 'Centre ville, Relizane'),
('Hub Yalidine Timimoun', 49, 'Yalidine', 'Centre ville, Timimoun'),
('Hub Yalidine Bordj Badji Mokhtar', 50, 'Yalidine', 'Centre ville, Bordj Badji Mokhtar'),
('Hub Yalidine Ouled Djellal', 51, 'Yalidine', 'Centre ville, Ouled Djellal'),
('Hub Yalidine Beni Abbes', 52, 'Yalidine', 'Centre ville, Beni Abbes'),
('Hub Yalidine In Salah', 53, 'Yalidine', 'Centre ville, In Salah'),
('Hub Yalidine In Guezzam', 54, 'Yalidine', 'Centre ville, In Guezzam'),
('Hub Yalidine Touggourt', 55, 'Yalidine', 'Centre ville, Touggourt'),
('Hub Yalidine Djanet', 56, 'Yalidine', 'Centre ville, Djanet'),
('Hub Yalidine El Meghaier', 57, 'Yalidine', 'Centre ville, El Meghaier'),
('Hub Yalidine El Meniaa', 58, 'Yalidine', 'Centre ville, El Meniaa');

-- =============================================
-- NOEST - Agences (principalement Est Algérie)
-- =============================================
INSERT OR IGNORE INTO stop_desks (name, wilaya_id, transporteur, address) VALUES
('Noest Batna Centre', 5, 'Noest', 'Centre ville, Batna'),
('Noest Bejaia', 6, 'Noest', 'Centre ville, Bejaia'),
('Noest Biskra', 7, 'Noest', 'Centre ville, Biskra'),
('Noest Tebessa', 12, 'Noest', 'Centre ville, Tebessa'),
('Noest Tizi Ouzou', 15, 'Noest', 'Centre ville, Tizi Ouzou'),
('Noest Alger Centre', 16, 'Noest', 'Centre ville, Alger'),
('Noest Setif Centre', 19, 'Noest', 'Centre ville, Setif'),
('Noest Setif El Eulma', 19, 'Noest', 'El Eulma, Setif'),
('Noest Skikda', 21, 'Noest', 'Centre ville, Skikda'),
('Noest Annaba Centre', 23, 'Noest', 'Centre ville, Annaba'),
('Noest Guelma', 24, 'Noest', 'Centre ville, Guelma'),
('Noest Constantine Centre', 25, 'Noest', 'Centre ville, Constantine'),
('Noest Constantine Ain Smara', 25, 'Noest', 'Ain Smara, Constantine'),
('Noest Oum El Bouaghi', 4, 'Noest', 'Centre ville, Oum El Bouaghi'),
('Noest Mila', 43, 'Noest', 'Centre ville, Mila'),
('Noest Souk Ahras', 41, 'Noest', 'Centre ville, Souk Ahras'),
('Noest El Tarf', 36, 'Noest', 'Centre ville, El Tarf'),
('Noest Khenchela', 40, 'Noest', 'Centre ville, Khenchela'),
('Noest Bordj Bou Arreridj', 34, 'Noest', 'Centre ville, Bordj Bou Arreridj'),
('Noest Boumerdes', 35, 'Noest', 'Centre ville, Boumerdes'),
('Noest Msila', 28, 'Noest', 'Centre ville, M''Sila'),
('Noest Jijel', 18, 'Noest', 'Centre ville, Jijel'),
('Noest El Oued', 39, 'Noest', 'Centre ville, El Oued'),
('Noest Touggourt', 55, 'Noest', 'Centre ville, Touggourt'),
('Noest Ouargla', 30, 'Noest', 'Centre ville, Ouargla');

-- =============================================
-- DHD - Agences
-- =============================================
INSERT OR IGNORE INTO stop_desks (name, wilaya_id, transporteur, address) VALUES
('DHD Alger Centre', 16, 'DHD', 'Rue Didouche Mourad, Alger'),
('DHD Alger Bab Ezzouar', 16, 'DHD', 'Bab Ezzouar, Alger'),
('DHD Alger Rouiba', 16, 'DHD', 'Zone industrielle, Rouiba'),
('DHD Blida', 9, 'DHD', 'Centre ville, Blida'),
('DHD Boumerdes', 35, 'DHD', 'Centre ville, Boumerdes'),
('DHD Tipaza', 42, 'DHD', 'Centre ville, Tipaza'),
('DHD Medea', 26, 'DHD', 'Centre ville, Medea'),
('DHD Tizi Ouzou', 15, 'DHD', 'Centre ville, Tizi Ouzou'),
('DHD Bejaia', 6, 'DHD', 'Centre ville, Bejaia'),
('DHD Setif', 19, 'DHD', 'Centre ville, Setif'),
('DHD Constantine', 25, 'DHD', 'Centre ville, Constantine'),
('DHD Annaba', 23, 'DHD', 'Centre ville, Annaba'),
('DHD Batna', 5, 'DHD', 'Centre ville, Batna'),
('DHD Oran Centre', 31, 'DHD', 'Centre ville, Oran'),
('DHD Oran Es Senia', 31, 'DHD', 'Es Senia, Oran'),
('DHD Tlemcen', 13, 'DHD', 'Centre ville, Tlemcen'),
('DHD Sidi Bel Abbes', 22, 'DHD', 'Centre ville, Sidi Bel Abbes'),
('DHD Mostaganem', 27, 'DHD', 'Centre ville, Mostaganem'),
('DHD Chlef', 2, 'DHD', 'Centre ville, Chlef'),
('DHD Ain Defla', 44, 'DHD', 'Centre ville, Ain Defla'),
('DHD Relizane', 48, 'DHD', 'Centre ville, Relizane'),
('DHD Mascara', 29, 'DHD', 'Centre ville, Mascara'),
('DHD Skikda', 21, 'DHD', 'Centre ville, Skikda'),
('DHD Biskra', 7, 'DHD', 'Centre ville, Biskra'),
('DHD Ouargla', 30, 'DHD', 'Centre ville, Ouargla'),
('DHD El Oued', 39, 'DHD', 'Centre ville, El Oued'),
('DHD Ghardaia', 47, 'DHD', 'Centre ville, Ghardaia'),
('DHD Laghouat', 3, 'DHD', 'Centre ville, Laghouat'),
('DHD Djelfa', 17, 'DHD', 'Centre ville, Djelfa'),
('DHD Tiaret', 14, 'DHD', 'Centre ville, Tiaret');

-- =============================================
-- ECOTRACK PDEX - Points de dépôt
-- =============================================
INSERT OR IGNORE INTO stop_desks (name, wilaya_id, transporteur, address) VALUES
('PDEX Alger Bab Ezzouar', 16, 'Ecotrack PDEX', 'Bab Ezzouar, Alger'),
('PDEX Alger Bir Mourad Rais', 16, 'Ecotrack PDEX', 'Bir Mourad Rais, Alger'),
('PDEX Alger Dar El Beida', 16, 'Ecotrack PDEX', 'Dar El Beida, Alger'),
('PDEX Blida Centre', 9, 'Ecotrack PDEX', 'Centre ville, Blida'),
('PDEX Boumerdes', 35, 'Ecotrack PDEX', 'Centre ville, Boumerdes'),
('PDEX Tizi Ouzou', 15, 'Ecotrack PDEX', 'Centre ville, Tizi Ouzou'),
('PDEX Bejaia', 6, 'Ecotrack PDEX', 'Centre ville, Bejaia'),
('PDEX Setif Centre', 19, 'Ecotrack PDEX', 'Centre ville, Setif'),
('PDEX Constantine', 25, 'Ecotrack PDEX', 'Centre ville, Constantine'),
('PDEX Annaba', 23, 'Ecotrack PDEX', 'Centre ville, Annaba'),
('PDEX Batna', 5, 'Ecotrack PDEX', 'Centre ville, Batna'),
('PDEX Oran Centre', 31, 'Ecotrack PDEX', 'Centre ville, Oran'),
('PDEX Oran Bir El Djir', 31, 'Ecotrack PDEX', 'Bir El Djir, Oran'),
('PDEX Tlemcen', 13, 'Ecotrack PDEX', 'Centre ville, Tlemcen'),
('PDEX Sidi Bel Abbes', 22, 'Ecotrack PDEX', 'Centre ville, Sidi Bel Abbes'),
('PDEX Biskra', 7, 'Ecotrack PDEX', 'Centre ville, Biskra'),
('PDEX Ouargla', 30, 'Ecotrack PDEX', 'Centre ville, Ouargla'),
('PDEX Skikda', 21, 'Ecotrack PDEX', 'Centre ville, Skikda'),
('PDEX Chlef', 2, 'Ecotrack PDEX', 'Centre ville, Chlef'),
('PDEX Bordj Bou Arreridj', 34, 'Ecotrack PDEX', 'Centre ville, Bordj Bou Arreridj'),
('PDEX Tipaza', 42, 'Ecotrack PDEX', 'Centre ville, Tipaza'),
('PDEX Medea', 26, 'Ecotrack PDEX', 'Centre ville, Medea'),
('PDEX El Oued', 39, 'Ecotrack PDEX', 'Centre ville, El Oued'),
('PDEX Ghardaia', 47, 'Ecotrack PDEX', 'Centre ville, Ghardaia'),
('PDEX Laghouat', 3, 'Ecotrack PDEX', 'Centre ville, Laghouat');
